name: geo_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - geopandas
  - rasterio
  - numpy
  - matplotlib
  - scipy
  - networkx
  - requests
  - osmnx 
  - pip
  - pip:
      - hda
      - python-dotenv
      - tqdm
<<<<<<< HEAD
      - elevation
=======
      - elevation
>>>>>>> 3d1a98d17e68e4453415f005fe9981489aa8f6fe
